apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: gcp-gke-template-update
  title: GCP - GKE (Kubernetes) - Update
  description: Update a GKE (Kubernetes) cluster in GCP
  tags:
    - infra
    - terraform
    - gcp
    - gke
spec:
  owner: group:infraops
  type: kubernetes

  parameters:
    # - title: About
    #   required:
    #     - component_id
    #   properties:
    #     component_id:
    #       title: Name
    #       type: string
    #       description: The unique name of the cluster
    #       ui:field: EntityNamePicker
    #     description:
    #       title: Description
    #       type: string
    #       description: Description of the cluster

    - title: Ownership
      required:
        - owner
      properties:
        owner:
          title: Owner
          type: string
          description: Owner of the cluster
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              - kind: Group

    - title: Configuration
      required:
        - region
      properties:
        region:
          title: GCP Region
          type: string
          description: GCP region of the cluster
          enum:
            - europe-west1
            - us-central1
            - asia-east1

    - title: Location
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch_component
      name: Fetch Component
      action: fetch:plain
      input:
        url: https://github.com/spotify-portal-public-demo/my-gke-cluster
        targetPath: component

    - id: template
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: https://github.com/spotify-portal-public-demo/gcp-gke-template-test/tree/main/skeleton
        targetPath: component
        replace: true
        values:
          component_id: my-gke-cluster
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          region: ${{ parameters.region }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}

    - id: debug
      name: Debug
      action: debug:log
      input:
        listWorkspace: true
