apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: gcp-gke-template-update
  title: GCP - GKE (Kubernetes) - Update
  description: Update a GKE (Kubernetes) cluster in GCP
  tags:
    - infra
    - terraform
    - gcp
    - gke
spec:
  owner: group:infraops
  type: kubernetes

  parameters:
    - title: Choose Entity
      required:
        - entity
      properties:
        entity:
          title: Entity
          type: string
          description: Entity to be updated
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              - kind: Resource
              # TODO: more filters
#                spec.type: team

  steps:
    - id: get_entity
      name: Get Entity
      action: catalog:fetch
      input:
        entityRef: ${{ parameters.entity }}

    - id: get_template
      name: Get Template
      action: catalog:fetch
      input:
        entityRef: ${{ steps.get_entity.output.entity.metadata.annotations['backstage.io/source-template'] }}

    - id: fetch_component
      name: Fetch Component
      action: fetch:plain
      input:
        url: ${{ steps.get_entity.output.entity.metadata.annotations['backstage.io/source-location'] | replace('url:', '') }}
        targetPath: component

    - id: read_params
      name: Read Params
      action: roadiehq:utils:fs:parse
      input:
        path: component/.template.json
        parser: json

    - id: template
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ${{ steps.get_template.output.entity.metadata.annotations['backstage.io/source-location'] | replace('url:', '') + 'skeleton' }}
        targetPath: component
        replace: true
        values: ${{ steps.read_params.output.content }}

    - id: debug
      name: Debug
      action: debug:log
      input:
        listWorkspace: true

    - id: update_pr
      name: Update PR
      action: publish:github:pull-request
      input:
        repoUrl: github.com?owner=spotify-portal-public-demo&repo=my-gke-cluster
        sourcePath: component
        branchName: update-${{ parameters.component_id }}
        title: update ${{ parameters.component_id }}
        description: This PR updates '${{ parameters.component_id }}'.

  output:
    links:
      - title: Update PR
        url: ${{ steps.update_pr.output.remoteUrl }}
