apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: gcp-gke-template-update
  title: GCP - GKE (Kubernetes) - Update
  description: Update a GKE (Kubernetes) cluster in GCP
  tags:
    - infra
    - terraform
    - gcp
    - gke
spec:
  owner: group:infraops
  type: kubernetes

  parameters:
    - title: Choose Component
      required:
        - component
      properties:
        component:
          title: Component
          type: string
          description: Component to update (does nothing for now)
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              - kind: Component
            allowArbitraryValues: false

  steps:
    - id: fetch_component
      name: Fetch Component
      action: fetch:plain
      input:
        url: https://github.com/external-spotify-portal-demo/my-gke-cluster
        targetPath: component

    - id: template
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: https://github.com/spotify-portal-public-demo/gcp-gke-template-test
        targetPath: component
        values:
          # TODO: need these
          component_id: ${{ parameters.component_id }}
          description: ${{ parameters.description }}
          owner: ${{ parameters.owner }}
          region: ${{ parameters.region }}
          destination: ${{ parameters.repoUrl | parseRepoUrl }}

    - id: debug
      name: Debug
      action: debug:log
      input:
        listWorkspace: true
